# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6b70f9d8e02b483b5c9b8da3dfe3dcbe6efbe8c23701a3f9404ed77cf1a38e9b0aec5f67b2eddaee69f2e05e4d4894daadedc14179167e7469149a68eb3c890

test:
  secret_key_base: 773f2fe09d38bba9b5240d2fb57e7214bf0ddf74395f68aed077686706a45dd640aae08ac16a05aea4d10c5c51597b33bbf234aad4c51600d7c5ccdbcde1e497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
